---
version: '3.6'

services:
  {{ service_name }}:

    image: "{{ image.repository }}:{{ image.tag }}"
    deploy:
      mode: {{ deploy.mode }}
      replicas: {{ deploy.replicas }}

{% if deploy.placement_constraints | length %}
      placement:
        constraints:
{% for p in deploy.placement_constraints %}
          - "{{ p }}"
{% endfor %}
{% endif %}

      labels:
{% if swarm-sync.managed %}
        - "swarm-sync.managed=true"
{% endif %}
{% if image.tag_pattern %}
        - "swarm-sync.image-pattern={{ image.tag_pattern }}"
{% endif %}
        - "traefik.port=3000"
        - "traefik.frontend.rule=Host:{{ traefik.hostname }}"
        - "traefik.backend.loadbalancer.stickiness={{ traefik.stickiness }}"

    environment:
{% for key, value in config %}
      SEMAPHORE_{{ key | upper }}: "{{ value }}"
{% endfor %}
