---
version: '3.3'

services:
  {{ service_name }}:
    image: "{{ image.repository }}:{{ image.tag }}"

    environment:
      AGENT_SECRET: {{ agent_secret }}

    deploy:
      labels:
        - "swarm-sync.managed={{ swarm_sync_managed }}"
        - "swarm-sync.image-pattern={{ image.tag_pattern }}"
{%  if traefik.enabled %}
        - "traefik.port={{ traefik.port }}"
        - "traefik.frontend.rule=Host:{{ traefik.hostname }}"
        - "traefik.backend.loadbalancer.stickiness={{ traefik.stickiness }}"
{% endif %}
{% if constrain_to_manager %}
      placement:
        constraints:
          - node.role == manager
{% endif %}
    volumes:
      - {{ portainer_data_volume }}:/data
{% if mount_docker_sock %}
      - /var/run/docker.sock:/var/run/docker.sock
{% endif %}

volumes:
  {{ portainer_data_volume }}: {}