---
service_name: traefik
image:
  repository: traefik
  tag: latest
  tag_pattern: latest
  auto: true
ssl_volume_name: traefik_ssl
swarm_sync_managed: true

environment: {}

ports:
  - { target: 433, published: 443, protocol: tcp, mode: ingress }
  - { target: 80, published: 80, protocol: tcp, mode: ingress }

enable_web: false

mount_docker_sock: true

args:
  - "--web"
  - "--defaultentrypoints=http,https"
  - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
  - "--entrypoints=Name:https Address::443 TLS"
  - "--docker.endpoint=unix:///var/run/docker.sock"
  - "--docker.exposedbydefault=true"

deploy:
  mode: global
  placement:
    constraints:
      - node.role == manager