---
service_name: traefik
image:
  repository: traefik
  tag: 1.7.11
  tag_pattern: semver:^1.7.11
ssl_volume_name: traefik_ssl
swarm_sync_managed: true

environment: {}

ports:
  - target: 443
    published: 443
    protocol: tcp
    mode: ingress
  - target: 80
    published: 80
    protocol: tcp
    mode: ingress

enable_web: false

mount_docker_sock: true

args:
  - "--web"
  - "--defaultentrypoints=http,https"
  - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
  - "--entrypoints=Name:https Address::443 TLS"
  - "--docker.endpoint=unix:///var/run/docker.sock"
  - "--docker.exposedbydefault=true"

deploy:
  mode: global
  placement:
    constraints:
      - node.role == manager

networks:
  default:
    driver: overlay
    attachable: true