---
version: '3.6'

services:
  {{ service_name }}:
    image: "{{ image.repository }}:{{ image.tag }}"

    command:
      - "--docker"
      - "--docker.swarmMode"
      - "--docker.watch"
  {% for arg in args %}
      - "{{ arg }}"
  {%- endfor %}

# Environment
{% for key, value in environment %}
{% if loop.first %}
    environment:
{% endif %}
      {{ key }}: {{ value }}
{% endfor %}

    # Deploy
    deploy:
      {{ deploy | dumpyml(6)}}
      labels:
        - "swarm-sync.managed={{ swarm_sync.managed }}"
        {% if image.tag_pattern %}- "swarm-sync.image-pattern={{ image.tag_pattern }}"{% endif %}

    # Logging
    {{ dumpblock_if_set({value: logging, indent: 4, root: 'logging'}) }}

    # Ports
    {{ dumpblock_if_set({value: ports, indent: 4, root: 'ports'}) }}

    networks:
    {%- for net, def in networks %}
      - {{ net }}
    {%- endfor %}

    volumes:
      - {{ ssl_volume_name }}:/etc/traefik/acme
    {% if mount_docker_sock %}
      - /var/run/docker.sock:/var/run/docker.sock
    {%- endif %}

## Other assets (not-service)
networks: {{ networks | dump }}
volumes:
  {{ ssl_volume_name }}: {}
