version: 2
jobs:
  build:
    docker:
      - image: node:12
    steps:
      - checkout
      - run: cd .circleci && npm i
      - run: node .circleci/build_publish.js

workflows:
  version: 2
  build_and_release:
    jobs:
      - build:
          filters:
            branches:
              only: master