---
version: '3.6'

services:
  {{ service_name }}:
    image: {{ image.repository }}:{{ image.tag }}

    environment:
      AGENT_CLUSTER_ADDR: tasks.{{ service_name }}
      AGENT_SECRET: {{ agent_secret }}

    ports:
      - target: 9001
        published: {{ host_port }}
        protocol: tcp
        mode: host

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

    # Deploy
    deploy:
      {{ deploy | dumpyml(6)}}
      labels:
      {% if swarm_sync.managed %}
        - "swarm-sync.managed=true"
      {%- endif %}
      {% if image.tag_pattern %}
        - "swarm-sync.image-pattern={{ image.tag_pattern }}"
      {%- endif %}
    # /Deploy

    networks:
    {%- for net, def in networks %}
      - {{ net }}
    {%- endfor %}

## Other assets (not-service)
networks: {{ networks | dump }}