---
version: '3.6'

services:
  {{ service_name }}:
    image: "{{ image.repository }}:{{ image.tag }}"

    environment:
    {% for pool, pool_def in config.pools %}
      MCROUTER_POOL_{{ pool }}: "{{ pool_def.hostname }}"
      MCROUTER_PORT_{{ pool }}: "{{ pool_def.port }}"
    {% endfor %}
      MCROUTER_ROUTE: "{{ config.route }}"
      MCROUTER_PORT: "{{ config.port }}"

    # Deploy
    deploy:
      {{ deploy | dumpyml(6)}}
      labels:
        - "swarm-sync.managed={{ swarm_sync.managed }}"
        {% if image.tag_pattern %}- "swarm-sync.image-pattern={{ image.tag_pattern }}"{% endif %}
    # /Deploy

    # Logging
    {{ dumpblock_if_set({value: logging, indent: 4, root: 'logging'}) }}

    networks:
    {%- for net, def in networks %}
      - {{ net }}
    {%- endfor %}

    # volumes:

## Other assets (not-service)
networks: {{ networks | dump }}
# volumes:
