---
version: '3.4'

services:
  {{ service_name }}:
    image: "{{ image.repository }}:{{ image.tag }}"

    environment:
      URL: {{ config.url }}
      REGISTRY_URL: {{ config.registry_url }}
      DELETE_IMAGES: {{ config.delete_images }}
      REGISTRY_TITLE: {{ config.registry_title }}
      PULL_URL: {{ config.pull_url }}

    # Deploy
    deploy:
      {{ deploy | dumpyml(6)}}
      labels:
    {% if swarm_sync_managed %}
        - "swarm-sync.managed=true"
    {%- endif %}
    {% if image.tag_pattern %}
        - "swarm-sync.image-pattern={{ image.tag_pattern }}"
    {%- endif %}
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:{{ traefik.hostname }}"
        - "traefik.backend.loadbalancer.stickiness={{ traefik.stickiness }}"
    # /Deploy

    # Logging
    {%- if logging | length %}
      {{logging}}: {{ logging | dump }}
    {%- endif %}
    # /Logging

    # Networks
    networks:
    {%- for net, def in networks %}
      - {{ net }}
    {%- endfor %}
    # /Networks

## Other assets (not-service)
networks: {{ networks | dump }}