---
version: '3.4'

services:
  {{ service_name }}:
    image: "{{ image.repository }}:{{ image.tag }}"
    deploy:
      mode: {{ deploy.mode }}
      replicas: {{ deploy.replicas }}
{% if deploy.placement_constraints | length %}
      placement:
        constraints:
{% for p in deploy.placement_constraints %}
          - "{{ p }}"
{% endfor %}
{% endif %}
      labels:
{% if swarm-sync.managed %}
        - "swarm-sync.managed=true"
{% endif %}
{% if image.tag_pattern %}
        - "swarm-sync.image-pattern={{ image.tag_pattern }}"
{% endif %}
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:{{ traefik.hostname }}"
        - "traefik.backend.loadbalancer.stickiness={{ traefik.stickiness }}"

    environment:
{% if config.user_filter | length %}
      DRONE_USER_FILTER: "{{ config.user_filter | join(',') }}"
{% endif %}
      DRONE_GIT_ALWAYS_AUTH: "{{ config.git_always_auth }}"
      DRONE_GITLAB_SERVER: "{{ config.gitlab_server }}"
      DRONE_GITLAB_CLIENT_ID: "{{ config.gitlab_client_id }}"
      DRONE_GITLAB_CLIENT_SECRET: "{{ config.gitlab_client_secret }}"
      DRONE_RUNNER_CAPACITY: "{{ config.runner_capacity }}"
      DRONE_SERVER_HOST: "{{ config.server_host }}"
      DRONE_SERVER_PROTO: "{{ config.server_proto }}"
      DRONE_TLS_AUTOCERT: "{{ config.tls_autocert }}"
      
    volumes:
      - {{ data_volume_name }}:/data
{% if mount_docker_sock %}
      - /var/run/docker.sock:/var/run/docker.sock
{% endif %}
volumes:
  {{ data_volume_name }}: {}
