---
version: '3.3'

services:
  swarm-sync:
    image: "{{ image.repository }}:{{ image.tag }}"
    volumes:
      - {{ volume }}:/run/swarm-sync
{% for v in additional_volumes %}
      - {{ v }}
{% endfor %}
    deploy:
      labels:
{% if swarm_sync_managed %}
        - "swarm-sync.managed=true"
{% endif %}
{% if image.tag_pattern %}
        - "swarm-sync.image-pattern={{ image.tag_pattern }}"
{% endif %}
{% if constrain_to_manager %}
      placement:
        constraints:
          - node.role == manager
{% endif %}
    secrets:
      - source: "{{ secret_from_value('swarm_sync_yml') }}"
        target: /etc/swarm-sync.yml
{% if git_crypt.enabled %}
      - source: "{{ secret_from_value('git_crypt.key', { base64: true }) }}"
        target: /run/secrets/git-crypt-key
{% endif %}
{% for s in secrets %}
      - source: "{{ secret_from_value(s.value, { name: s.name }) }}"
        target: "{{ s.target }}"
{% endfor %}
{% if id_rsa.enabled %}
      - source: "{{ secret_from_value('id_rsa.key') }}"
        target: /root/.ssh/id_rsa
        mode: 0600
{% endif %}
    stop_grace_period: {{ stop_grace_period }}

volumes:
  {{ volume }}: {}