---
version: '3.3'

services:
  swarm-sync:
    image: "{{ image.repository }}:{{ image.tag }}"

    # Volumes
    volumes:
      - {{ volume }}:/run/swarm-sync
  {% for v in additional_volumes %}
      - {{ v }}
  {%- endfor %}
    # /Volumes

    # Deploy
    deploy:
      {{ deploy | dumpyml(6)}}
      labels:
    {% if swarm_sync_managed %}
        - "swarm-sync.managed=true"
    {%- endif %}
    {% if image.tag_pattern %}
        - "swarm-sync.image-pattern={{ image.tag_pattern }}"
    {%- endif %}
    # /Deploy

    # Secrets
    secrets:
      - source: "{{ secret_from_value('swarm_sync_yml') }}"
        target: /etc/swarm-sync.yml
{% if git_crypt.enabled %}
      - source: "{{ secret_from_value('git_crypt.key', { base64: true }) }}"
        target: /run/secrets/git-crypt-key
{% endif %}
{% if id_rsa.enabled %}
      - source: "{{ secret_from_value('id_rsa.key') }}"
        target: /root/.ssh/id_rsa
        mode: 0600
{% endif %}
{% for s in secrets %}
      - source: "{{ secret(s.name, s.value) }}"
        target: "{{ s.target }}"
{% endfor %}
    # /Secrets

    stop_grace_period: {{ stop_grace_period }}

    {%- if logging | length %}
      {{logging}}: {{ logging | dump }}
    {%- endif %}

volumes:
  {{ volume }}: {}