---
version: '3.6'

services:
  {{ service_name }}:

    image: "{{ image.repository }}:{{ image.tag }}"

    environment:
      PORT: {{ config.port }}
      ROOT_URL: {{ config.root_url }}
      {% if config.mail_url %}MAIL_URL: {{ config.mail_url }}{% endif %}
      ADMIN_USERNAME: {{ config.admin_username }}
      ADMIN_EMAIL: {{ config.admin_email }}
      ADMIN_PASS: {{ config.admin_password }}
      MONGO_URL: {{ config.mongo_url }}
      MONGO_OPLOG_URL: {{ config.mongo_oplog_url }}

    # Deploy
    deploy:
      {{ deploy | dumpyml(6)}}
      labels:
        - "swarm-sync.managed={{ swarm_sync.managed }}"
        {% if image.tag_pattern %}- "swarm-sync.image-pattern={{ image.tag_pattern }}"{% endif %}
        - "traefik.port={{ config.port }}"
        - "traefik.frontend.rule=Host:{{ traefik.hostname }}"
        - "traefik.backend.loadbalancer.stickiness={{ traefik.stickiness }}"
        {% if traefik.network %}- "traefik.docker.network={{ traefik.network }}"{% endif %}
    # /Deploy

    # Logging
    {{ dumpblock_if_set({value: logging, indent: 4, root: 'logging'}) }}

    networks:
    {%- for net, def in networks %}
      - {{ net }}
    {%- endfor %}

    volumes:
      - {{ uploads_volume_name }}:/app/uploads

## Other assets (not-service)
networks: {{ networks | dump }}

volumes:
  {{ uploads_volume_name }}: {}